Repository mergifyio-testing/functional-testing-repo-ErwanSimonetti, pull requests merged in 2021-09, with the labels that each got.

#160 test_merge_priority: pull request n1 from fork
  test1
Labels: high

#161 test_merge_priority: pull request n2 from fork
  test2
Labels: medium

#167 test_merge_smart_ordered: pull request n1 from origin
  test1
Labels: ready

#172 test_merge_smart_unordered: pull request n3 from origin
  test3
Labels: ready

#182 test_batch_queue: pull request n1 from fork
  test1
Labels: queue

#183 test_batch_queue: pull request n2 from fork
  test2-moved
Labels: queue

#191 test_batch_split_queue: pull request n1 from fork
  test1
Labels: queue

#192 test_batch_split_queue: pull request n2 from fork
  test2-moved
Labels: queue

#334 test_merge_priority: pull request n1 from fork
  test1
Labels: high

#335 test_merge_priority: pull request n2 from fork
  test2
Labels: medium

#341 test_merge_smart_legacy: pull request n1 from origin
  test1
Labels: ready

#344 test_merge_smart_ordered: pull request n1 from origin
  test1
Labels: ready

#349 test_merge_smart_unordered: pull request n3 from origin
  test3
Labels: ready

#360 test_batch_split_queue: pull request n1 from fork
  test1
Labels: queue

#361 test_batch_split_queue: pull request n2 from fork
  test2-moved
Labels: queue

#608 test_merge_priority: pull request n1 from fork
  test1
Labels: high

#609 test_merge_priority: pull request n2 from fork
  test2
Labels: medium

#615 test_merge_smart_legacy: pull request n1 from origin
  test1
Labels: ready

#618 test_merge_smart_ordered: pull request n1 from origin
  test1
Labels: ready

#623 test_merge_smart_unordered: pull request n3 from origin
  test3
Labels: ready

#633 test_batch_queue: pull request n1 from fork
  test1
Labels: queue

#634 test_batch_queue: pull request n2 from fork
  test2-moved
Labels: queue

#849 test_merge_priority: pull request n1 from fork
  test1
Labels: high

#850 test_merge_priority: pull request n2 from fork
  test2
Labels: medium

#856 test_merge_smart_legacy: pull request n1 from origin
  test1
Labels: ready

#859 test_merge_smart_ordered: pull request n1 from origin
  test1
Labels: ready

#864 test_merge_smart_unordered: pull request n3 from origin
  test3
Labels: ready

#872 test_batch_queue: pull request n1 from fork
  test1
Labels: queue

#873 test_batch_queue: pull request n2 from fork
  test2-moved
Labels: queue

#891 test_batch_queue: pull request n1 from fork
  test1
Labels: queue

#892 test_batch_queue: pull request n2 from fork
  test2-moved
Labels: queue

#908 test_batch_queue: pull request n1 from fork
  test1
Labels: queue

#909 test_batch_queue: pull request n2 from fork
  test2-moved
Labels: queue

#925 test_batch_queue: pull request n1 from fork
  test1
Labels: queue

#926 test_batch_queue: pull request n2 from fork
  test2-moved
Labels: queue

#951 test_batch_split_queue: pull request n1 from fork
  test1
Labels: queue

#952 test_batch_split_queue: pull request n2 from fork
  test2-moved
Labels: queue

#964 test_batch_split_queue: pull request n1 from fork
  test1
Labels: queue

#965 test_batch_split_queue: pull request n2 from fork
  test2-moved
Labels: queue

#982 test_batch_split_queue: pull request n1 from fork
  test1
Labels: queue

#983 test_batch_split_queue: pull request n2 from fork
  test2-moved
Labels: queue

#1177 test_merge_priority: pull request n1 from fork
  test1
Labels: high

#1178 test_merge_priority: pull request n2 from fork
  test2
Labels: medium

#1184 test_merge_smart_legacy: pull request n1 from origin
  test1
Labels: ready

#1187 test_merge_smart_ordered: pull request n1 from origin
  test1
Labels: ready

#1192 test_merge_smart_unordered: pull request n3 from origin
  test3
Labels: ready

#1197 test_batch_queue: pull request n1 from fork
  test1
Labels: queue

#1206 test_batch_split_queue: pull request n1 from fork
  test1
Labels: queue

#1207 test_batch_split_queue: pull request n2 from fork
  test2-moved
Labels: queue
